WITH BASE_2017 AS (
    SELECT DISTINCT 
        EXTRACT(YEAR FROM DATA_VENDA) || "-" || EXTRACT(MONTH FROM DATA_VENDA) AS ANO_MES,
        SUM(QTD_VENDA) AS QTD_VENDAS
    FROM `tabelas_boticario.base_2017`
    GROUP BY EXTRACT(YEAR FROM DATA_VENDA) || "-" || EXTRACT(MONTH FROM DATA_VENDA)
),
BASE_2019 AS (
    SELECT DISTINCT 
        EXTRACT(YEAR FROM DATA_VENDA) || "-" || EXTRACT(MONTH FROM DATA_VENDA) AS ANO_MES,
        SUM(QTD_VENDA) AS QTD_VENDAS
    FROM `tabelas_boticario.base_2019`
    GROUP BY EXTRACT(YEAR FROM DATA_VENDA) || "-" || EXTRACT(MONTH FROM DATA_VENDA)
)
SELECT 
    ANO_MES,
    QTD_VENDAS
FROM BASE_2017 
UNION ALL 
SELECT 
    ANO_MES,
    QTD_VENDAS
FROM BASE_2019
